### ISSUE TITLE
VS 2022 support

### ISSUE THREAD

**Issue by ekarcnevets** [ow--/vs-subword-navigation#14]
Please would you consider adding support for VS2022? I've gotten so used to having your extension it's hard to live without it, thank you!

Here is a link to documentation:
https://docs.microsoft.com/en-us/visualstudio/extensibility/migration/update-visual-studio-extension?view=vs-2022

**Comment by ow--** [comment]
Hm. That was a fair bit of work. But I suppose I'm going to want it myself sooner or later. I'll put it on the mental backlog.

**Comment by ekarcnevets** [comment]
Much appreciated!

**Comment by reduckted** [comment]
Good news! Because this extension is very simple, it doesn't need to be split into multiple projects to support Visual Studio 2022. 🎉 

I've created PR #15 to add VS2022 support.
