### ISSUE TITLE
Edit.SubwordNext skips entire C# comments

### ISSUE THREAD

**Issue by hellfirehd** [ow--/vs-subword-navigation#17]
First, let me say that I love this plugin! I am so lost without it when other apps (especially web browsers) do not have subword navigation.

Howwever, `Edit.SubwordNext ` now skips from the beginning of // comments to the end in one shot.  If you move the cursor into the comment and then use `Edit.SubwordNext` it works as expected. 

This is new as I am sure it worked perfectly before. 

I am using Microsoft Visual Studio Community 2022 (64-bit) - Preview v17.11.0 Preview 1.0. `Edit.SubwordNext ` so maybe it is related to the preview.

Please let me know how I can assist with troubleshooting this.

**Comment by hellfirehd** [comment]
Just installed the non-preview Visual Studio Community 2022. It is still skipping from the beginning of a single line comment to the end. As with the preview version of VS2022 it works fine if you are starting from within the comment.

**Comment by ow--** [comment]
Thanks, happy to have been of service. Is this the same as #5, do you think? Or something else?

**Comment by hellfirehd** [comment]
Yes, that looks precisely like what I am encountering. If it has been this way for some time then I have no idea why I never noticed before. Well, other than maybe because I do not write enough comments in my code. :p 

Incidentally, I am Doug Wilson from the [Developer Community thread](https://developercommunity.visualstudio.com/t/subword-navigation-aka-camel-humps-in-editor/377108?from=email&viewtype=all#T-ND1508694) linked in #5.
