### ISSUE TITLE
VS 2017 Edit.Subword[...] keyboard mappings keep clearing

### ISSUE THREAD

**Issue by roryap** [ow--/vs-subword-navigation#3]
I have had this happen twice to me where the keyboard mappings I've entered for the subword commands all get wiped out.  It works for a couple weeks, then randomly they're gone.  I'm not sure whether VS is causing the problem, but I can't figure out how to stop it.

**Comment by ow--** [comment]
I've never had this issue myself, but I have several friends and co-workers that experience this regularly, some for years, without running this extension. At least to my knowledge.

I've always assumed they do something weird, but the VS team seems to finally be acknowledging it, at least for VS2017, and are working to resolve the reverting settings.

https://developercommunity.visualstudio.com/content/problem/61488/vs2017-still-constantly-losing-keyboard-mappings.html
https://developercommunity.visualstudio.com/content/problem/41680/keyboard-customizations-loss.html

So fingers crossed this resolves itself shortly. In the meantime, could it be mitigated by exporting your settings and importing the backup when this happens maybe?
