### ISSUE TITLE
Add instructions on which key bindings to change, or add an autoconfig button somewhere

### ISSUE THREAD

**Issue by miss-programgamer** [ow--/vs-subword-navigation#8]
Currently, the extension does not automatically override the user's settings. This is fine, but the extension page also doesn't provide instructions on how to manually configure the extension, which may be confusing since it then appears to not work out of the box.

Simply mentioning which key bindings need to be unbound and others rebound would help, but it would also be nice if there was a button somewhere that would automatically override the current bindings, for convenience.

For reference, you need to go to `Tools>Options>Environment>Keyboard` and unset the following bindings:

- Edit.WordDeleteToEnd
- Edit.WordDeleteToStart
- Edit.WordNext
- Edit.WordNextExtend
- Edit.WordPrevious
- Edit.WordPreviousExtend

And then set the following while making sure that the `Use the new shortcut in:` dropdown is set to `Text Editor`:

- Edit.SubwordDeleteNext (Ctrl+Del)
- Edit.SubwordDeletePrevious (Ctrl+Backspace)
- Edit.SubwordNext (Ctrl+RightArrow)
- Edit.SubwordNextExtend (Ctrl+Shift+RightArrow)
- Edit.SubwordPrevious (Ctrl+LeftArrow)
- Edit.SubwordPreviousExtend (Ctrl+Shift+LeftArrow)

I know you know this already since you're the person who made the extension, but that way you can just copy-paste all this into the description with minimal effort ;)

**Comment by patlaundy** [comment]
After installing the extension and setting the shortcuts it wasn't working. This was the exact fix, thank you. We should get this added to the readme file.

**Comment by ow--** [comment]
This was more or less by design. I didn't want to override anyone's settings and I personally don't want to override normal behavior on Ctrl but rather add these commands on Alt. I was never gonna satisfy everyone with the default and I didn't want to put a lot of effort into the configuration.

Maybe I'll attempt to be slightly more helpful in the readme.
